name: 01 - Building Blocks
on: [push, workflow_dispatch]

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, world!"

  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Successful step
        run: |
          echo "I will succeed"
          exit 0
      - name: Say goodbye
        run: |
            echo "Goodbye!"
            exit 0