name: 05 - 1 - Event Filters and Activity Types
on: 
    pull_request:
        types: [opened, synchronize, closed]
        branches:
            - main
            - 'release/**'
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
        - run: Running whenever a PR is closed

